; [env:proton]
; platform = raspberrypi
; board = proton
; framework = picosdk
; upload_protocol = picotool
; ; Remove the 'debug_tool' line to stop the error
; monitor_speed = 115200

[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
upload_protocol = picoprobe
monitor_speed = 115200