// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// matrix_pio //
// ---------- //

#define matrix_pio_wrap_target 0
#define matrix_pio_wrap 1
#define matrix_pio_pio_version 0

#define matrix_pio_offset_entry_point 0u

static const uint16_t matrix_pio_program_instructions[] = {
            //     .wrap_target
    0x6006, //  0: out    pins, 6         side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program matrix_pio_program = {
    .instructions = matrix_pio_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = matrix_pio_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config matrix_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + matrix_pio_wrap_target, offset + matrix_pio_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

